package constants

const (
	ServerName                  = "server-name"
	FileName                    = "file-name"
	ProxyMgrPort                = "proxy-mgr-port"
	InBoundProxyPort            = "in-bound-proxy-port"
	OutBoundProxyPort           = "out-bound-proxy-port"
	UDPProxyPort                = "udp-proxy-port"
	ConnIdleTimeOut             = "conn-idle-time-out"
	CacheFileName               = "cache-file-name"
	CacheDuration               = "cache-duration"
	DomainPolicyURL             = "domain-policy-url"
	DomainPolicyCacheFile       = "domain-policy-cache-file"
	DomainPolicyRefreshInterval = "domain-policy-refresh-interval"
	DomainPolicyFetchTimeout    = "domain-policy-fetch-timeout"
	DomainPolicyScope           = "domain-policy-scope"
	AppName                     = "app-name"
	InstanceIP                  = "instance-ip"
	MITMEnabled                 = "mitm-enabled"
	VaultURI                    = "vault-uri"
	AgentID                     = "agent-id"
	UpstreamCAFile              = "upstream-ca-file"
	CAPollInterval              = "ca-poll-interval"
	CAInitTimeout               = "ca-init-timeout"
	CredentialRuntimeCacheFile  = "credential-runtime-cache-file"
	CredentialRuntimeRefresh    = "credential-runtime-refresh-interval"
	CredentialRuntimeFetch      = "credential-runtime-fetch-timeout"
)
